# Generated by Django 5.0.4 on 2024-04-09 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "codigo_produto",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("produto", models.CharField(max_length=100)),
                ("codigo_de_barrar", models.CharField(max_length=100)),
                ("valor_de_venda", models.FloatField()),
                ("quantidade_em_estoque", models.IntegerField()),
                ("valor_compra", models.FloatField()),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Compra",
            fields=[
                (
                    "codigo_venda",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("data_venda", models.DateTimeField(auto_now_add=True)),
                ("quantidade_venda", models.IntegerField()),
                ("cliente", models.CharField(max_length=100)),
                (
                    "produto_compra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mercado.produto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vendas",
            fields=[
                (
                    "codigo_venda",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("data_venda", models.DateTimeField(auto_now_add=True)),
                ("quantidade_venda", models.IntegerField()),
                ("fornecedor", models.CharField(max_length=100)),
                (
                    "produto_venda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mercado.produto",
                    ),
                ),
            ],
        ),
    ]
